### ISSUE TITLE
The two mitochondrial SLIMP subunits should be added to the SerRS alignment

### ISSUE THREAD

**Issue by jordandouglas** [aarsonline/aarsonline.github.io#60]
Thanks for the suggestion Lluis

**Comment by jordandouglas** [comment]
SLIMP from Lingula anatina has been added to the database. There were issues getting the Drosophila form to work on AlphaFold

**Comment by RibasdePouplana** [comment]
Hi Jordan,

just getting used to this. First comment: it'd be nice to get a Drosophila SLIMP sequence on.
I am not sure about Lingula (it probably is fine), but I am sure that the active site ablation
is obvious in Drosophila sequences. By the way, is there a way to indicate motif degeneration
in the site ?

**Comment by jordandouglas** [comment]
I'll try again to get a drosophila structure on there. Alphafold didnt like the one I gave it but I'll give it another go. 

How would you suggest we indicate motif degenation on the figure? I can't think of a current way of doing that but if you can think of a clean way of visualising it, I can implement something

**Comment by jordandouglas** [comment]
I found a drosophila slimp on the alphafold database - I added that one to the page
