### ISSUE TITLE
Every family should have the human structures (cytosolic and mitochondrial)

### ISSUE THREAD

**Issue by jordandouglas** [aarsonline/aarsonline.github.io#64]

**Comment by mariesissler** [comment]
I was also (mostly) thinking about the human SEQUENCES (both cytosolic and mitochondrial), but I understand it can be an issue to introduce that into all the different subsections ( Domain architecture, Primary structure, Secondary structure, ....)

**Comment by jordandouglas** [comment]
The structures and sequences are coupled, meaning that every sequence appears in the first 3 sections and its structure appears further down. Adding a new sequence/structure involves 1) finding a structure (solved or or alphafold), 2) running a script that realigns all of the structures/sequences on a webpage, and 3) manually adjusting the alignment if any regions aligned poorly.
So not an issue at all
